# Generated by Django 4.1.7 on 2023-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField(max_length=15)),
                ('coursename', models.CharField(max_length=250)),
                ('Price', models.IntegerField(max_length=15)),
            ],
        ),
    ]
