# Generated by Django 4.1.7 on 2023-05-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
