# Generated by Django 4.1.7 on 2023-05-24 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class', '0004_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=250)),
                ('videonumber', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=25)),
                ('section', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateTimeField()),
            ],
        ),
    ]
